version: '3.4'

services:
  samba:
    container_name: Samba
    image: dperson/samba
    environment:
      TZ: "America/New_York"
      USERID: id -u ${USER}
      GROUPID: id -g ${USER}
      USER: "robert;uscrules1"
    #ports:
      #- "137:137/udp"
      #- "138:138/udp"
      #- "139:139/tcp"
      #- "445:445/tcp"
    read_only: false
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ~/mount/backups:/mnt
    command: '-s "backups;/mnt;no;no;no;robert;all;${USER}"'
    networks:
      macvlan_network:
        ipv4_address: 100.64.0.4

networks:
  macvlan_network:
    external:
      name: mynet