version: '3.4'

services:
  samba:
    image: dperson/samba
    environment:
      TZ: 'EST5EDT'
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/test:/mnt:z
    command: '-s "Mount;/mnt"'
    networks:
      macvlan_network:
        ipv4_address: 100.64.0.4

networks:
  macvlan_network:
    external:
      name: mynet